######################################################################
# Automatically generated by qmake (3.1) Tue Jul 1 14:04:34 2025
######################################################################

TEMPLATE = app
TARGET = LoginPage
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += databasemanager.h \
           mainapplication.h \
           mainwindow.h \
           build/LoginPage_autogen/include/ui_mainwindow.h \
           build/Desktop_Qt_6_9_1_MinGW_64_bit-Debug/LoginPage_autogen/include/ui_mainwindow.h \
           /build/LoginPage_autogen/include/ui_mainwindow.h \
           build/LoginPage_autogen/EWIEGA46WW/moc_databasemanager.cpp \
           build/LoginPage_autogen/EWIEGA46WW/moc_mainapplication.cpp \
           build/LoginPage_autogen/EWIEGA46WW/moc_mainwindow.cpp \
           build/Desktop_Qt_6_9_1_MinGW_64_bit-Debug/LoginPage_autogen/EWIEGA46WW/moc_databasemanager.cpp \
           build/Desktop_Qt_6_9_1_MinGW_64_bit-Debug/LoginPage_autogen/EWIEGA46WW/moc_mainapplication.cpp \
           build/Desktop_Qt_6_9_1_MinGW_64_bit-Debug/LoginPage_autogen/EWIEGA46WW/moc_mainwindow.cpp
FORMS += mainwindow.ui
SOURCES += check_drivers.cpp \
           databasemanager.cpp \
           main.cpp \
           mainapplication.cpp \
           mainwindow.cpp \
           simple_test.cpp \
           test_http.cpp \
           test_mysql_connection.cpp \
           /test_http.cpp \
           build/LoginPage_autogen/mocs_compilation.cpp \
           build/Desktop_Qt_6_9_1_MinGW_64_bit-Debug/LoginPage_autogen/mocs_compilation.cpp \
           CMakeFiles/4.0.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Desktop_Qt_6_9_1_MinGW_64_bit-Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/Desktop_Qt_6_9_1_MinGW_64_bit-Debug/CMakeFiles/4.0.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
